#include"globalConst.h"


#define ID_YUFFIE_TEACHER_REAGENT_APPLY_TITLE_LAB 1801
#define ID_YUFFIE_TEACHER_REAGENT_APPLY_LIST 1802
#define ID_YUFFIE_TEACHER_REAGENT_ADD_BUTTON 1803
#define ID_YUFFIE_TEACHER_REAGENT_DELETE_BUTTON 1804
#define ID_YUFFIE_TEACHER_REAGENT_COMMIT_BUTTON 1805



BOOL CALLBACK ReagentApplyDlgProc(HWND, UINT, WPARAM, LPARAM);