#include"globalConst.h"


#define ID_YUFFIE_ADMIN_REVIEW_APPLY_TITLE_LAB 1201
#define ID_YUFFIE_ADMIN_REVIEW_APPLY_LIST 1202
#define ID_YUFFIE_ADMIN_REVIEW_APPLY_FINISH_BUTTON 1203
#define ID_YUFFIE_ADMIN_REVIEW_APPLY_DELETE_BUTTON 1204

BOOL CALLBACK ReviewApplyDlgProc(HWND, UINT, WPARAM, LPARAM);