#include"globalConst.h"


#define ID_YUFFIE_ADMIN_USER_TITLE_LAB 1501
#define ID_YUFFIE_ADMIN_USER_LIST 1502
#define ID_YUFFIE_ADMIN_USER_DELETE_BUTTON 1503
#define ID_YUFFIE_ADMIN_USER_MANAGE_BUTTON 1504
#define ID_YUFFIE_ADMIN_USER_ADD_BUTTON 1505
BOOL CALLBACK UserManageDlgProc(HWND, UINT, WPARAM, LPARAM);