#include"globalConst.h"

#define ID_YUFFIE_ADMIN_REVIEW_OFFER_TITLE_LAB 1301
#define ID_YUFFIE_ADMIN_REVIEW_OFFER_LIST 1302
#define ID_YUFFIE_ADMIN_REVIEW_OFFER_DELETE_BUTTON 1303
#define ID_YUFFIE_ADMIN_REVIEW_OFFER_CHEAP_DELETE_BUTTON 1304
#define ID_YUFFIE_ADMIN_REVIEW_OFFER_FINISH_BUTTON 1305


#define CM_SHOW_LIST 1399


BOOL CALLBACK ReviewOfferDlgProc(HWND, UINT, WPARAM, LPARAM);