#include"globalConst.h"


#define ID_YUFFIE_ADMIN_LAB_TITLE_LAB 1401
#define ID_YUFFIE_ADMIN_LAB_LIST 1402
#define ID_YUFFIE_ADMIN_LAB_PURCHASE_BUTTON 1403
#define ID_YUFFIE_ADMIN_LAB_PRINT_BUTTON 1404
#define ID_YUFFIE_ADMIN_LAB_MANAGE_BUTTON 1405

BOOL CALLBACK MainLabDlgProc(HWND, UINT, WPARAM, LPARAM);