#include"globalConst.h"

#define ID_YUFFIE_BEGIN_BUTTON 200
#define ID_YUFFIE_ABOUT_BUTTON 201
#define ID_YUFFIE_VESION_LAB 202

/*
    @value:°´Å¥×ø±ê¡¢¿í¸ß¡£
*/
#define YUFFIE_BEGIN_BUTTON_X 280
#define YUFFIE_BEGIN_BUTTON_Y 350
#define YUFFIE_BEGIN_BUTTON_WIDTH 200
#define YUFFIE_BEGIN_BUTTON_HEIGHT 50
#define YUFFIE_CX_CLIENT 750
#define YUFFIE_CY_CLIENT 350


#define YUFFIE_ABOUT_BUTTON_X 280
#define YUFFIE_ABOUT_BUTTON_Y 430
#define YUFFIE_ABOUT_BUTTON_WIDTH 200
#define YUFFIE_ABOUT_BUTTON_HEIGHT 50


LRESULT CALLBACK HallWndProc(HWND, UINT, WPARAM, LPARAM);
