#include"globalConst.h"

#define ID_YUFFIE_ADMIN_ADD_USER_LAB 1501
#define ID_YUFFIE_ADMIN_ADMIN_RADIO_BUTTON 1502
#define ID_YUFFIE_ADMIN_TEACHER_RADIO_BUTTON 1503
#define ID_YUFFIE_ADMIN_SUPPLIER_RADIO_BUTTON 1504
#define ID_YUFFIE_ADMIN_USERNAME_LAB 1505
#define ID_YUFFIE_ADMIN_PASSWORD_LAB 1506
#define ID_YUFFIE_ADMIN_USERNAME_EDIT 1507
#define ID_YUFFIE_ADMIN_PASSWORD_EDIT 1508
#define ID_YUFFIE_ADMIN_ADD_USER_FINISH_BUTTON 1509

BOOL CALLBACK UserAddDlgProc(HWND, UINT, WPARAM, LPARAM);