#include"globalConst.h"

#define ID_YUFFIE_TEACHER_LOGOUT_BUTTON 1005
#define ID_YUFFIE_TEACHER_WECOME_LAB 1006
#define ID_YUFFIE_TEACHER_NAME_LAB 1007
#define ID_YUFFIE_TEACHER_PURCHASE_APPLY_BUTTON 1008
#define ID_YUFFIE_TEACHER_REAGENT_APPLY_BUTTON 1009
#define ID_YUFFIE_TEACHER_REPERTORY_MANAGE_BUTTON 1010

/*
    @function:´°¿Ú¹ý³Ì¡£
*/
LRESULT CALLBACK TeacherWndProc(HWND, UINT, WPARAM, LPARAM);