#include"globalConst.h"


#define ID_YUFFIE_ADMIN_NAME_LAB 1001
#define ID_YUFFIE_ADMIN_PURCHASE_PLAN_BUTTON 1002
#define ID_YUFFIE_ADMIN_REAGENT_APPLY_BUTTON 1003
#define ID_YUFFIE_USER_MANAGE_BUTTON 1004
#define ID_YUFFIE_ADMIN_LOGOUT_BUTTON 1005
#define ID_YUFFIE_ADMIN_WECOME_LAB 1006
#define ID_YUFFIE_ADMIN_ALL_RADIO_BUTTON 1007
#define ID_YUFFIE_ADMIN_GEL_RADIO_BUTTON 1008
#define ID_YUFFIE_ADMIN_SPE_RADIO_BUTTON 1009
#define ID_YUFFIE_ADMIN_LAB_BUTTON 1010
/*
    @function:窗口过程。
*/
LRESULT CALLBACK AdminWndProc(HWND, UINT, WPARAM, LPARAM);