#include"globalConst.h"


#define ID_YUFFIE_TEACHER_REVIEW_APPLY_TITLE_LAB 1201
#define ID_YUFFIE_ADMIN_REVIEW_APPLY_LIST 1202
#define ID_YUFFIE_ADMIN_REVIEW_APPLY_FINISH_BUTTON 1203
#define ID_YUFFIE_ADMIN_REVIEW_APPLY_DELETE_BUTTON 1204

#define ID_YUFFIE_TEACHER_PURCHASE_APPLY_TITLE_LAB 1205
#define ID_YUFFIE_TEACHER_PURCHASE_APPLY_LIST 1206
#define ID_YUFFIE_TEACHER_PURCHASE_ADD_BUTTON 1207
#define ID_YUFFIE_TEACHER_PURCHASE_DELETE_BUTTON 1208
#define ID_YUFFIE_TEACHER_PURCHASE_COMMIT_BUTTON 1209



BOOL CALLBACK TeacherApplyDlgProc(HWND, UINT, WPARAM, LPARAM);