#include"globalConst.h"

#define ID_YUFFIE_ADMIN_NOTICE_TITLE_LAB 1101
#define ID_YUFFIE_ADMIN_NOTICE_INPUTE_EDIT 1102
#define ID_YUFFIE_ADMIN_NOTICE_CONFIRM_BUTTON 1103

/*
    @function:"窗口过程。"
*/
BOOL CALLBACK AnnoucementDlgProc(HWND, UINT, WPARAM, LPARAM);